### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by XuecWu** [BriansIDP/AudioVisualLLM#3]
Thank you for your great work.
When the code implementations will be available?

Looking forward to your reply.
Thanks a lot.

**Comment by BriansIDP** [comment]
Hi. Thank you for your interest. We are still in the process of finalising the camera-ready version of our paper and will release the code as soon as possible. Sorry for the delay.

**Comment by XuecWu** [comment]
Thank you for your reply!
Looking forward to the code release!
